# Generated by Django 3.1.4 on 2021-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Duyurular'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Haberler'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
