# Generated by Django 3.1.4 on 2021-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0002_auto_20210526_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default=' ', max_length=300, verbose_name='title'),
        ),
    ]
