# Generated by Django 3.1.4 on 2021-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0005_auto_20210527_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='automatıons',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='students',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
