# Generated by Django 3.1.4 on 2021-05-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0006_auto_20210527_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatıons',
            name='see',
        ),
        migrations.RemoveField(
            model_name='automatıons',
            name='slug',
        ),
    ]
