# Generated by Django 3.1.4 on 2021-05-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0007_auto_20210527_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatıons',
            name='content',
        ),
    ]
