# Generated by Django 3.1.4 on 2021-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0008_remove_automatıons_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisementss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='İlan Başlıgı ')),
                ('content', models.TextField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Advertisementss_imgs/')),
                ('see', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='İlanı Haberi Gören Kişi Sayısı')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'İLANLAR',
            },
        ),
    ]
