# Generated by Django 3.1.4 on 2021-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0009_advertisementss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisements',
        ),
    ]
